### PR TITLE
feat: add GONE to /validate responses

### PR DESCRIPTION
**Pull request by charlesc-ifit**
from [this suggestion](https://github.com/ifit/ifit/pull/17033#discussion_r643537893), which was done in the same PR in [this commit](https://github.com/ifit/ifit/commit/02599695851e150f0170651cf2aa09f6dcd5e8be)

### CODE REVIEW

**Review by ZachHawkes — APPROVED** [review]
Looks great to me!

**Comment by jeffy-ifit** [comment]
I actually intended for this to be thrown in the:
```js
{
  isEntitled: false,
  error: {
    code :410,
    ...
    retryable: false
  }
```
block 🤔, but it doesn't hurt either to proxy it back wholesale

**Comment by charlesc-ifit** [comment]
> I actually intended for this to be thrown in the...

sorry, I jumped the gun, you're totally right. I forgot that IAP errors were gonna be a resp 200, `isEntitled = false` + error info (including the retryable flag). I'll close this and get to fixing the code/tests.

**Comment by jeffy-ifit** [comment]
@charlesc-ifit 👍 I still wonder if this was a poor choice, but I've already committed to this design decision lol 😓...

**Pull request closed without merging**
